apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  data: AgDjkNg1EfJiJAQk1UMod/5YhxDj8oYmXod/IrTyr58UNVeKRDGUBzNzaMZXwd+4CdlV+rPH7l+P1Zhzj3b2DAnjZIIFDLF/gy/2eQDBgya/4kH0Kpvl5G6TX0i3TjLGFTLugaQkVGhwK39kORUEJM/9/yp5kwhS4zO54IdqD4OQyoP0icWJtFxkAbdipQB0aE8lyB0ZmFHPiCyrShepg6zs3yyI3Uqy99Sjg/fOLz1byQHX1yRDO2rsdQI97o6z8l10Li1W8dILVUP4UxNDivCqXzSn1yKxlAMwVp7YG1MeK0IV/LItKE/J4dE3zC45KLZhdLH0gabM4UQ/4XbnuzjlIfOSFBzZLjZN2K5xIoCqOsIRf3AHjLDMRj2kxIvIhDk+QpJowziDz9LAMBuTdQ7bk59tjiYeC6wZePDfAVDstIVBuFxLZ0VjJd/B86+Hl/7WOxrurB5D+yOojbNrmbrbXKLTXooU+tFqV4lnOGNVOmtMENb1AXFYC9iHCxGZdTzXjz4TheuTblm+rH43NKXLGBNpGJJMpLv2R8LzBEVtQgAODUmCMRIehtwuvMmqPkym6F4A0xP4CLY2SAcVCZypqyiKkpdwOeb6tWfmFdgfc/FvfDgux1yyYsiUeFmmCrO4l66B+mGXn9EHl6bKN+2LH8DhlXJlw5f/k7tvpieJeknGaOmMpx8gfGmU6ELm3ZFlfZkm10Q1zt5YjXKHR64Yrof5L2Tw4rLQqNr9lstYGgZbOD+S3iv7RDzDxrn3SYKzNhkH+4/0KcFMrXCWfux7ZA/vn8GFzvBgL2sd7NrSeqScPsqxshe7uHPPy3NHR5kQAYS5uvfz+6J/vK83177CRT11PPGxPtgpqXJYiu2qaF/64MIhj/bWQEjOLLNh6c2oxsgXFQdyJaX6tau94x2lEg==

