---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
#    flux.weave.works/locked: 'true'
#    flux.weave.works/locked_msg: '"Halt updates for now"'
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:linuxbsdfreak/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    #image: linuxbsdfreak/podinfo:dev-poz07gbk
    image: abapcp-k8s.docker.repositories.sap.ondemand.com/k8s-podinfo:dev-ppookwrw
    secret: registry-secrets-dev
    replicaCount: 1
    hpa:
      enabled: false
