---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:linuxbsdfreak/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    #image: linuxbsdfreak/podinfo:0.4.15
    image: abapcp-k8s.docker.repositories.sap.ondemand.com/k8s-podinfo:0.4.12
    secret: registry-secrets-prod
    replicaCount: 1
