---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:linuxbsdfreak/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    #image: linuxbsdfreak/podinfo:stg-7id4w4nk
    image: abapcp-k8s.docker.repositories.sap.ondemand.com/k8s-podinfo:stg-7id4w4nk
    secret: image-pull-secret  
    replicaCount: 1
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
