---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-reg-secret
  namespace: prod
spec:
  data: AgAFjqeWx1YwZ6nTVbL5Fuwku7TrYLFCNy4YDbswEIRn/76USSpXMxLkQHvcnB8mwkBq/EzJD/4t1hvINo9epNQKxSGemx5FxMNpVT14oQlTydfIYk91mxhbXqAWvIPMTj7M0KYBOgwrdRKVh2j9P5dFHAWK16HowlHNfjSMcwy9gOFyAFekeRu16c5mneyq/jOb6iuY5xVScZK6B6HuAnxOS3+PzC7rG78BULR899DvmTfxpmFC4pakrnigx/BQsqlooIoM2yJiM6mJIueSt3uztpTU7Chzte1ots6Dwf0Kbi1ICHnbCkoI906h4ol/l93W2x/ijSQ4EcX4PGHDMJ4IoY8AfLKNbK+HYpkq5D036Vrb61wFDGCoD8850rfAJ2vZS+z7l6oLee/DXlLYxCg84E3feW5yQbUYk+oBtMGuZLkzmiyrUq+wtvzqbRLj2IEAMrMzOI+811J9zI7BZPjBM2KHux0CJYrCD0awx/2hd1w0GdG7W+2ZNyGJtiDd29wzpORVfjMWZBHgSGorlMp1ZEci/HFsO0aQThnofl2HAlAUmlI1RaVTvtJqYZNL6aj9ZluYQrXJEdgWu8fmOPM1YPXKOV5fD6ly3Ir9ytvS7qVDIRyB6eQQapCVPC0kqltefvBuDOrJGb7pPp6E2gZf7y3PiJMBmKgv8/G8mHCfnt9gAPZ1Sd9+JtYv9O8Y+w2UD/KWlJO/lFZxpMzD54E2EtvVHOS8adNuERCibodkgtaLklF/yiyah2puXpGcH3c/fysOFFMlydE7I98MKTz91HR7X7IlT+sIzHDS0BLl+HqJlFTrTXPykcZUT5L/syzq1QF2Zy4Vu+uoEfyowShtyQtG8BfREgDBo4eU3lt5NlAzPPUfiLc93DmM57QTFcYmqpLM2fc/h7Ki5YzFKCBW+IzxeEmIkrkMlYupdl7xMYDEKZJZlcuDJAbLSf9lYXUwLAnHjochC9+iOSNYVZ9603PRCJ0NSsnHgy6BfpK1DV316J/Jsf6SQPfALTqCs01swBS6pDZdygyNAJUymsEX+NUmmYp7aePSQn3Rd4f4YzkaPLtm8i/I9MCCJE0r5IkXnl/aNN1fXUZ8ttvUEafZtvBphlTL9+JSJqxVFxtKioRMIcOew8qZsQpBPS0YRxALJDrTIqj8rFt9zeAOj+TU5UmxVdT9JiEpA3F7nG36ch4stUjlbVQN5dCU5lHwB1UEBYWLzWHmBqxBUlH9fc3BxwnsrzENAIoHK70RWCjVis4k5YA0aBGqtpxZAOYjbZyygR937tgLZHlLmlDP6PrmBMWZCarn7pWY7WpnculdVaD9qmwY8g/O
