---
apiVersion: v1
kind: Namespace
metadata:
  name: stg
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-reg-secret
  namespace: stg
spec:
  data: AgDT/DYtkb7NzSWF6xecIWU/ejOKL6m9BqYi7vM4YZufpnQ05agOJ5fHkO+PwGUWEuy0KJzi1UqaWMnJhbLUnQCz2iQoLPPqckCi/i/6IGyv2KE8JG3H2mpKIj406xmzhhYzJhH7nX8D+3DS3VrUMqjRf06JARE5Fn3fSQTES9DkBxZiFQ67GVytrhCIrrUjrTmsLR16BG4Qgxm/4/bTJNhICTYA4IbkGXdemgx+yW7A7vBo0P0OoWLTNZ2e8f6VgyZxp0cX/CsXOX+lDJB2zoeJr59+69UPW3WXCDyShb+hcdiTTybmnJJLc2r83pK4kc/boJuNBqB6/Q5qaGqB8OGb22cxg/xyf4ByZbifH/1NfEAG+ycIdxsT1uhlKQt/HPaOOqWqic42ZbvcdEd1/Jnhn5UO8uA3nDwDRaSIoXw1UFqXrEcsjU6dZ/4+4oOfyl9loqahCXRYEulw5xdxPtYQdQwD+iHTC5v17iM0lEqLIzbK1sx/EIZi5ABD63DtHmsKns3FgaupvpDEKMkjZNwN32iOWBtkT9H6RiV3wOOHQGlHXyLYR2hd5rF+Z1RIzatf0Nq4i2MRVyJjnAnZvJ4N/6wlRpLu0WUoApg6fxUJPvZ22wvM3Qm/7ZT/8G+0ddl2fKmOVtLQDLbjnplC9sOoIchjc2As/jGi4RAS0wUyDRu6WE7zFPosUzzbZFtNXSPUTKtSx0+czez/w/xm8jp/5e+iLf2rQ5pkV9huH4URWU6jUmMyd2MsItLw6CKhQY8xIrTagD9xju5hxIaMZRW+niC43VlFa2iwxgcC7xDhtRlJnTqpMoF4fB2Mji6SZM8iOuQrvlub8DJn0Wb5SGXCLwZPaWGE7tWenZ1NSFFBM+O2GWz3IhmtCylzs5pumVM05fuAjzR0euNkavrQQH6XmrFy9A2fbo6TdHD4k8JRKMNcovhVZPZngACXfnqe/HMMXeO2+Y/BUk08Y7Jbdgz1YnUyjQ9z6yTo1cyJm7Ox2+P0GR88w5FX8hT+s5E4zGq6FDXMnjH5EceCTS3JJWx1KtWj1bIXB6r5gbHYFPlkaAloFN7vdeCzXG8A8+WuZa8KbPssgFiveN9ZB64nBETyxdHms4srbwH1vrOXSXLeEXf7F/2y2bmOt199DTSAWBiwG3rrLCLcYHYtZ2O6e6Vjv03pwblb+OMoKz7/JgJA1ruPz/DuvT89NqAxnCkfokJcYq4y/5L9822TYdRFFMvoLG2FOUzYn1EO2zoCJYOSYqMHT656JrLIQmSP3BN16yMV4qDdBbMF69mCfn2JWhXhs9ot8FZi7SD0usbj5pj/IxOOk7uSnZM=
